Big Data Real-Time Analytics com Python e Spark

Capítulo 2 - Manipulação de Dados em Python com NumPy

In [3]:
# Versão da linguagem python
from platform import python_version
print('Versão do python:', python_version())

Versão do python: 3.9.13


In [4]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comnado:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark.
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [5]:
# Importando o módulo NumPy
import numpy as np

In [9]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a 'Data Science Academy' --iversions

Author: Data Science Academy

numpy: 1.22.3



In [8]:
# Instalando uma versão específica do NumPy
!pip install numpy==1.22.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 10.2 MB/s eta 0:00:00m eta 0:00:010:01:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.22.3 which is incompatible.


Criando Estruturas de Dados NumPy

In [11]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40])

In [12]:
print(array1)

[10 20 30 40]


In [16]:
# Verificando o formado (shape) do array
array1.shape

(4,)

In [17]:
# Verificando o numero de dimensões
array1.ndim

1

In [18]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15], [42, 78, 0]])

In [19]:
print(array2)

[[100  83  15]
 [ 42  78   0]]


In [20]:
array2.shape

(2, 3)

In [22]:
array2.ndim

2

Em Python TUDO é Objeto, com Métodos e Atributos

Método - Realiza ação no objeto

Atributo - Característica (propriedade) do objeto

In [23]:
# Método
array2.max()

100

In [24]:
# Atributo
array2.ndim

2

Criando Estruturas de Dados com Arange

In [26]:
array3 = np.arange(15)

In [27]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 3)

In [29]:
array4

array([ 0,  3,  6,  9, 12])

Criando Estruturas de Dados com Linspace

In [34]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

Criando Estruturas de Dados com Outras Funções

numpy.zeros

In [33]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

numpy.ones

In [35]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

numpy.eye

In [36]:
# Produz uma Matriz Identidade
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Matriz diagonal
array9 = np.diag((2, 1, 4, 6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

numpy.random.rand

In [39]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [40]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

numpy.empty

In [41]:
array12 = np.empty((3,2)); array12

array([[1.83504755e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

numpy.tile

In [42]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [43]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [44]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

Tipos de Dados NumPy

In [45]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [46]:
print(array13)

[ 8. -3.  5.  9.]


In [47]:
array13.dtype

dtype('float64')

In [48]:
array14 = np.array([2, 4, 6, 8])

In [49]:
print(array14)

[2 4 6 8]


In [50]:
array14.dtype

dtype('int64')

In [54]:
array15 = np.array([2.0, 4, 6, 8])

In [55]:
print(array15)

[2. 4. 6. 8.]


In [56]:
array15.dtype

dtype('float64')

In [57]:
array16 = np.array(['Ingo', 'Reichert', 'Junior'])

In [58]:
array16.dtype

dtype('<U8')

In [59]:
array17 = np.array([True, False, True])

In [60]:
array17.dtype

dtype('bool')

In [61]:
array18 = np.array([7, -3, 5.24])

In [62]:
array18.dtype

dtype('float64')

In [63]:
array18.astype(int)

array([ 7, -3,  5])

Operações com Arrays

In [64]:
# Array começando por 0, com 30 elementos e multiplicado por 5
array19 = np.arange(0, 30) * 5

In [65]:
print(array19)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145]


In [66]:
# Elevando um array a quarta potência
array20 = np.arange(5) ** 4

In [67]:
array20

array([  0,   1,  16,  81, 256])

In [68]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [69]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [71]:
array22 = np.arange(0, 30, 3) + 3
array23 = np.arange(1,11)

In [72]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [73]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [76]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [77]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [78]:
# Podemos ainda comparar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [80]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido.

In [87]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

3.09 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [88]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

250 µs ± 2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
